image: fedora:latest
include:
  - component: gitlab.gnome.org/GNOME/citemplates/release-service@master
    inputs:
      job-stage: release
      dist-job-name: "build-release-tarball"
      tarball-artifact-path: "${TARBALL_ARTIFACT_PATH}"

stages:
  - test
  - release

variables:
  DEPENDENCIES: gettext gettext-devel gcc git help2man libadwaita-devel meson gtk4-devel yelp-tools webkitgtk6.0-devel
  GIT_SUBMODULE_STRATEGY: normal
  MESON_BUILD_DIR: _build
  TARBALL_ARTIFACT_PATH: "${MESON_BUILD_DIR}/meson-dist/${CI_PROJECT_NAME}-${CI_COMMIT_TAG}.tar.xz"

test:
  stage: test
  before_script:
    - dnf update -y --nogpgcheck
    - dnf install -y --nogpgcheck $DEPENDENCIES
  script:
    - meson setup "${MESON_BUILD_DIR}"
    - meson test -C "${MESON_BUILD_DIR}"
    - ninja -C "${MESON_BUILD_DIR}" install

build-release-tarball:
  stage: release
  needs: ["test"]
  before_script:
    - dnf update -y --nogpgcheck
    - dnf install -y --nogpgcheck $DEPENDENCIES
  script:
    - meson setup "${MESON_BUILD_DIR}"
    - meson dist -C "${MESON_BUILD_DIR}"
  artifacts:
    name: "${CI_JOB_NAME}-${CI_COMMIT_REF_NAME}"
    when: always
    paths:
      - "${TARBALL_ARTIFACT_PATH}"
  rules:
    - if: '$CI_COMMIT_TAG'