.TH ZENITY 1 "January 2022"
.SH NAME
zenity \- display GTK+ dialogs
.SH SYNOPSIS
.B zenity
.RI [ options ]
.SH DESCRIPTION
\fBzenity\fP is a program that will display GTK+ dialogs, and return
(either in the return code, or on standard output) the users
input. This allows you to present information, and ask for information
from the user, from all manner of shell scripts.
.PP
For example, \fBzenity \-\-question\fP will return either 0, 1 or 5,
depending on whether the user pressed \fIOK\fP, \fICancel\fP or timeout
has been reached. \fBzenity \-\-entry\fP will output on standard output
what the user typed into the text entry field.
.PP
Comprehensive documentation is also available in the GNOME Help Browser.

.SH OPTIONS
This program follows the usual GNU command line syntax, with long
options starting with two dashes (`-').

.SS
Dialog Options

.PP
Options can be used in various combinations in order to craft many different
types of dialogs.

.PP
For a summary of options, run \fBzenity \-\-help\fP.  This will display the
first hierarchy of options available. A separate series of help sub-categories
for each of these options will be displayed.

.PP
For a full and complete list of all options for your build and an explanation
of these options, run \fBzenity \-\-help\-all\fP

.SS
Miscellaneous options

.TP
.B \-?, \-\-help
Show summary of options.
.TP
.B \-\-about
Display an about dialog.
.TP
.B \-\-version
Show version of program.

.SH EXAMPLES

Display a file selector with the title \fISelect a file to
remove\fP. The file selected is returned on standard output.
.IP
zenity  \-\-title="Select a file to remove" \-\-file-selection
.PP
Display a text entry dialog with the title \fISelect Host\fP and the
text \fISelect the host you would like to flood-ping\fP. The entered
text is returned on standard output.
.IP
zenity  \-\-title "Select Host" \-\-entry \-\-text "Select the host you would like to flood-ping"
.PP
Display a dialog, asking \fIMicrosoft Windows has been found! Would
you like to remove it?\fP. The return code will be 0 (true in shell)
if \fIOK\fP is selected, and 1 (false) if \fICancel\fP is selected.
.IP
zenity  \-\-question \-\-title "Alert"  \-\-text "Microsoft Windows has been found! Would you like to remove it?"
.PP
Show the search results in a list dialog with the title \fISearch Results\fP
and the text \fIFinding all header files...\fP.
.IP
find . \-name '*.h' | zenity \-\-list \-\-title "Search Results" \-\-text "Finding all header files.." \-\-column "Files"
.PP
Show a passive notification
.IP
zenity \-\-notification \-\-icon=update.png \-\-text "System update necessary!"
.PP
Display a weekly shopping list in a check list dialog with \fIApples\fP and \fIOranges\fP pre selected
.IP
zenity \-\-list \-\-checklist \-\-column "Buy" \-\-column "Item" TRUE Apples TRUE Oranges FALSE Pears FALSE Toothpaste
.PP
Display a progress dialog while searching for all the postscript files in your home directory
.P
find $HOME \-name '*.ps' | zenity \-\-progress \-\-pulsate
.SH AUTHOR
\fBZenity\fP was written by Glynn Foster <glynn.foster@sun.com>.
.P
This manual page was written by Ross Burton <ross@burtonini.com>.

.SH SEE ALSO
\fBdialog\fP(1)
