.TH ZENITY 1 "December 2011"
.SH NAME
zenity \- display GTK+ dialogs
.SH SYNOPSIS
.B zenity
.RI [ options ]
.SH DESCRIPTION
\fBzenity\fP is a program that will display GTK+ dialogs, and return
(either in the return code, or on standard output) the users
input. This allows you to present information, and ask for information
from the user, from all manner of shell scripts.
.PP
For example, \fBzenity \-\-question\fP will return either 0, 1 or 5,
depending on whether the user pressed \fIOK\fP, \fICancel\fP or timeout
has been reached. \fBzenity --entry\fP will output on standard output
what the user typed into the text entry field.
.PP
Comprehensive documentation is available in the GNOME Help Browser.
.SH OPTIONS
This program follows the usual GNU command line syntax, with long
options starting with two dashes (`-').

.PP
Dialog options

.TP
.B \-\-calendar
Display calendar dialog
.TP
.B \-\-entry
Display text entry dialog
.TP
.B \-\-error
Display error dialog
.TP
.B \-\-file\-selection
Display file selection dialog
.TP
.B \-\-info
Display info dialog
.TP
.B \-\-list
Display list dialog
.TP
.B \-\-notification
Display notification
.TP
.B \-\-progress
Display progress indication dialog
.TP
.B \-\-question
Display question dialog
.TP
.B \-\-text-info
Display text information dialog
.TP
.B \-\-warning
Display warning dialog
.TP
.B \-\-scale
Display scale dialog
.TP
.B \-\-color-selection
Display color selection dialog
.TP
.B \-\-password
Display password dialog
.TP
.B \-\-forms
Display forms dialog

.PP
General options

.TP
.B \-\-title=TITLE
Set the dialog title
.TP
.B \-\-window-icon=ICONPATH
Set the window icon with the path to an image. Alternatively, one of the four stock icons can be used: 'error', 'info', 'question' or 'warning'
.TP
.B \-\-width=WIDTH
Set the dialog width
.TP
.B \-\-height=HEIGHT
Set the dialog height
.TP
.B \-\-timeout=TIMEOUT
Set the dialog timeout in seconds
.PP 
Calendar options

.TP
.B \-\-text=STRING
Set the dialog text
.TP
.B \-\-day=INT
Set the calendar day
.TP
.B \-\-month=INT
Set the calendar month
.TP
.B \-\-year=INT
Set the calendar year
.TP
.B \-\-date-format=PATTERN
Set the format for the returned date. The default depends on the user locale or be set with the strftime style. For example %A %d/%m/%y

.PP
Text entry options

.TP
.B \-\-text=STRING
Set the dialog text
.TP
.B \-\-entry-text=STRING
Set the entry text
.TP
.B \-\-hide-text
Hide the entry text

.PP
Error options
.TP
.B \-\-text=STRING
Set the dialog text
.TP
.B \-\-no\-wrap
Do not enable text wrapping
.TP
.B \-\-no\-markup
Do not enable pango markup

.PP
File selection options
.TP
.B \-\-filename=FILENAME
Set the file or directory to be selected by default
.TP
.B \-\-multiple
Allow selection of multiple filenames in file selection dialog
.TP
.B \-\-directory
Activate directory-only selection
.TP
.B \-\-save
Activate save mode
.TP
.B \-\-separator=SEPARATOR
Specify separator character when returning multiple filenames
.TP
.B \-\-confirm\-overwrite
Confirm file selection if filename already exists
.TP
.B \-\-file\-filter=NAME | PATTERN1 PATTERN2
Sets a filename filter


.PP
Info options
.TP
.B \-\-text=STRING
Set the dialog text
.TP
.B \-\-no\-wrap
Do not enable text wrapping
.TP
.B \-\-no\-markup
Do not enable pango markup

.PP
List options

.TP
.B \-\-text=STRING
Set the dialog text
.TP
.B \-\-column=STRING
Set the column header
.TP
.B \-\-checklist
Use check boxes for first column
.TP
.B \-\-radiolist
Use radio buttons for first column
.TP
.B \-\-separator=STRING
Set output separator character
.TP
.B \-\-multiple
Allow multiple rows to be selected
.TP
.B \-\-editable
Allow changes to text
.TP
.B \-\-print-column=NUMBER
Specify what column to print to standard output. The default is to return
the first column. 'ALL' may be used to print all columns.
.TP
.B \-\-hide\-column=NUMBER
Hide a specific column
.TP
.B \-\-hide\-header
Hides the column headers

.PP
Notification options

.TP
.B \-\-text=STRING
Set the notification text
.TP
.B \-\-listen
Listen for commands on stdin. Commands include 'message', 'tooltip', 'icon', and 'visible' separated by a colon. For example, 'message: Hello world', 'visible: false', or 'icon: /path/to/icon'. The icon command also accepts the four stock icon: 'error', 'info', 'question', and 'warning'

.PP
Progress options

.TP
.B \-\-text=STRING
Set the dialog text
.TP
.B \-\-percentage=INT
Set initial percentage
.TP
.B \-\-auto\-close
Close dialog when 100% has been reached
.TP
.B \-\-auto\-kill
Kill parent process if cancel button is pressed
.TP
.B \-\-pulsate
Pulsate progress bar
.TP
.B \-\-no\-cancel
Hides the cancel button

.PP
Question options

.TP
.B \-\-text=STRING
Set the dialog text
.TP
.B \-\-no\-wrap
Do not enable text wrapping
.TP
.B \-\-no\-markup
Do not enable pango markup
.TP
.B \-\-ok\-label
Set the text of the OK button
.TP
.B \-\-cancel\-label
Set the text of the cancel button

.PP
Text options

.TP
.B \-\-filename=FILENAME
Open file
.TP
.B \-\-editable
Allow changes to text
.TP
.B \-\-checkbox=TEXT
Enable a checkbox for use like a 'I read and accept the terms.'
.TP
.B \-\-ok\-label
Set the text of the OK button
.TP
.B \-\-cancel\-label
Set the text of the cancel button

.PP
Warning options

.TP
.B \-\-text=STRING
Set the dialog text
.TP
.B \-\-no\-wrap
Do not enable text wrapping
.TP
.B \-\-no\-markup
Do not enable pango markup

.PP
Scale options

.TP
.B \-\-text=STRING
Set the dialog text
.TP
.B \-\-value=VALUE
Set initial value
.TP
.B \-\-min\-value=VALUE
Set minimum value
.TP
.B \-\-max\-value=VALUE
Set maximum value
.TP
.B \-\-step=VALUE
Set step size
.TP
.B \-\-print\-partial
Print partial values
.TP
.B \-\-hide\-value
Hide value

.PP
Color selection options

.TP
.B \-\-color=VALUE
Set the initial color
.TP
.B \-\-show\-palette
Show the palette

.PP
Password dialog options

.TP
.B \-\-username
Display the username field

.PP
Forms dialog options

.TP
.B \-\-add\-entry=FIELDNAME
Add a new Entry in forms dialog
.TP
.B \-\-add\-password=FIELDNAME
Add a new Password Entry in forms dialog
.TP
.B \-\-add\-calendar=FIELDNAME
Add a new Calendar in forms dialog
.TP
.B \-\-text=STRING
Set the dialog text
.TP
.B \-\-separator=STRING
Set output separator character
.TP
.B \-\-forms\-date-format=PATTERN
Set the format for the returned date. The default depends on the user locale or be set with the strftime style. For example %A %d/%m/%y

.PP
Miscellaneous options

.TP
.B \-?, \-\-help
Show summary of options.
.TP
.B \-\-about
Display an about dialog.
.TP
.B \-\-version
Show version of program.

.PP
Also the standard GTK+ options are accepted. For more information about the GTK+ options, execute following command.
.IP
zenity \-\-help\-gtk

.SH ENVIRONMENT

Normally, zenity detects the terminal window from which it was launched and
keeps itself above that window.  This behavior can be disabled by unsetting the
WINDOWID environment variable.

.SH EXAMPLES

Display a file selector with the title \fISelect a file to
remove\fP. The file selected is returned on standard output.
.IP
zenity  \-\-title="Select a file to remove" \-\-file-selection
.PP
Display a text entry dialog with the title \fISelect Host\fP and the
text \fISelect the host you would like to flood-ping\fP. The entered
text is returned on standard output.
.IP
zenity  \-\-title "Select Host" \-\-entry \-\-text "Select the host you would like to flood-ping"
.PP
Display a dialog, asking \fIMicrosoft Windows has been found! Would
you like to remove it?\fP. The return code will be 0 (true in shell)
if \fIOK\fP is selected, and 1 (false) if \fICancel\fP is selected.
.IP
zenity  \-\-question \-\-title "Alert"  \-\-text "Microsoft Windows has been found! Would you like to remove it?"
.PP
Show the search results in a list dialog with the title \fISearch Results\fP
and the text \fIFinding all header files...\fP.
.IP
find . \-name '*.h' | zenity \-\-list \-\-title "Search Results" \-\-text "Finding all header files.." \-\-column "Files"
.PP
Show a notification in the message tray
.IP
zenity \-\-notification \-\-window-icon=update.png \-\-text "System update necessary!"
.PP
Display a weekly shopping list in a check list dialog with \fIApples\fP and \fIOranges\fP pre selected
.IP
zenity \-\-list \-\-checklist \-\-column "Buy" \-\-column "Item" TRUE Apples TRUE Oranges FALSE Pears FALSE Toothpaste
.PP
Display a progress dialog while searching for all the postscript files in your home directory
.P
find $HOME \-name '*.ps' | zenity \-\-progress \-\-pulsate
.SH AUTHOR
\fBZenity\fP was written by Glynn Foster <glynn.foster@sun.com>.
.P
This manual page was written by Ross Burton <ross@burtonini.com>.

.SH SEE ALSO
\fBgdialog\fP(1), \fBdialog\fP(1)
